# Generated by Django 4.2.1 on 2023-06-05 09:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="directmessage",
            name="status",
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
