# Generated by Django 4.2.1 on 2023-06-07 10:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0002_directmessage_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="directmessage",
            name="status",
        ),
        migrations.AddField(
            model_name="directmessage",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="media"),
        ),
    ]
