# Generated by Django 4.2.1 on 2023-06-08 06:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0003_remove_directmessage_status_directmessage_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="directmessage",
            name="file",
            field=models.ImageField(blank=True, null=True, upload_to="media"),
        ),
    ]
