# Generated by Django 4.2.1 on 2023-06-12 11:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0004_alter_directmessage_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="directmessage",
            name="file_url",
            field=models.URLField(blank=True),
        ),
    ]
