# Generated by Django 4.2.1 on 2023-06-13 04:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0005_directmessage_file_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="directmessage",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="media"),
        ),
    ]
